CREATE TABLE IF NOT EXISTS USERS (
    ID VARCHAR (50) NOT NULL PRIMARY KEY,
    NAME VARCHAR (50) NOT NULL,
    SURNAME VARCHAR (50),
    PHONE VARCHAR (50),
    EMAIL VARCHAR (50),
    LOGIN VARCHAR (50) NOT NULL,
    LOGO VARCHAR (50),
    VERSION BIGINT DEFAULT 1,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UC_USER_LOGIN UNIQUE (LOGIN)
);


CREATE TABLE IF NOT EXISTS FILES
(
    ID        VARCHAR(255) NOT NULL PRIMARY KEY,
    DIRECTORY  VARCHAR(255) NOT NULL,
    FORMAT     VARCHAR(255) NOT NULL,
    URL        VARCHAR(255) NOT NULL,
    VERSION BIGINT DEFAULT 1,
    CREATED_AT TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS CITY (
     ID VARCHAR (50) NOT NULL PRIMARY KEY,
     NAME VARCHAR (50) NOT NULL,
     VERSION BIGINT DEFAULT 1,
     CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     CONSTRAINT UC_CITY_NAME UNIQUE (NAME)
);


CREATE TABLE IF NOT EXISTS AUTHORITY (
    ID VARCHAR (50) NOT NULL PRIMARY KEY,
    NAME VARCHAR (50) NOT NULL,
    DESCRIPTION VARCHAR (255) NOT NULL,
    VERSION BIGINT DEFAULT 1,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UC_AUTHORITY_NAME UNIQUE (NAME)
);

CREATE TABLE IF NOT EXISTS USER_AUTHORITY (
  ID VARCHAR (100) NOT NULL PRIMARY KEY,
  USER_ID VARCHAR (100) NOT NULL REFERENCES USERS (ID) ON DELETE CASCADE,
  AUTHORITY_ID VARCHAR (100) NOT NULL REFERENCES AUTHORITY (ID) ON DELETE CASCADE,
  VERSION BIGINT DEFAULT 1,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);